# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"USER_HOME": "00_conf.ipynb",
         "API_ENDPOINT": "00_conf.ipynb",
         "CLI_ENDPOINT": "00_conf.ipynb",
         "TIGHTAI_LOCAL_DIR_NAME": "00_conf.ipynb",
         "TIGHTAI_LOCAL_DIRECTORY": "00_conf.ipynb",
         "TIGHTAI_LOCAL_CREDENTIALS": "00_conf.ipynb",
         "TIGHTAI_LOCAL_PROJECTS_DIR": "00_conf.ipynb",
         "TIGHTAI_BASE_TIGHTIGNORE": "00_conf.ipynb",
         "CredentialHandler": "01_handlers.ipynb",
         "credentials": "01_handlers.ipynb",
         "ArgumentsRequired": "02_exceptions.ipynb",
         "RequestError": "02_exceptions.ipynb",
         "ProjectDoesNotExist": "02_exceptions.ipynb",
         "VersionDoesNotExist": "02_exceptions.ipynb",
         "InvalidProjectVersion": "02_exceptions.ipynb",
         "AUTH_PATH": "03_auth.ipynb",
         "Auth": "03_auth.ipynb",
         "auth": "03_auth.ipynb",
         "path": "03_auth.ipynb",
         "login": "03_auth.ipynb",
         "logout": "03_auth.ipynb",
         "signup": "03_auth.ipynb",
         "Lookup": "04_lookup.py.ipynb",
         "Uploader": "05_upload.ipynb",
         "BaseObject": "06_projects.ipynb",
         "UserObject": "06_projects.ipynb",
         "VersionManager": "06_projects.ipynb",
         "Version": "06_projects.ipynb",
         "ProjectManager": "06_projects.ipynb",
         "Project": "06_projects.ipynb",
         "load_run_handler": "07_local.ipynb",
         "read_root": "07_local.ipynb",
         "server_app": "07_local.ipynb",
         "parse_cli_args": "07_local.ipynb",
         "sort_by_key": "10_utils.ipynb"}

modules = ["conf.py",
           "handlers.py",
           "exceptions.py",
           "auth.py",
           "lookup.py",
           "upload.py",
           "projects.py",
           "local.py",
           "utils.py"]

doc_url = "https://tightai.github.io/tightai/"

git_url = "https://github.com/tightai/tightai/tree/master/"

def custom_doc_links(name): return None
