# AUTOGENERATED! DO NOT EDIT! File to edit: 10_user.ipynb (unless otherwise specified).

__all__ = ['UserObject']

# Cell
from .base import BaseObject

# Cell
class UserObject(BaseObject):
    def __str__(self):
        return f"<User: {self.username}>"